import React from "react";

export const options = [
  { value: "LHC", label: "LHC" },
  { value: "Old Mess", label: "Old Mess" },
  { value: "New Mess", label: "New Mess" },
  { value: "PHC", label: "PHC" },
  { value: "Library", label: "Library" },
  { value: "Admin Block", label: "Admin Block" },
  { value: "Athletics Ground", label: "Athletics Ground" },
  { value: "Hostel B1", label: "Hostel B1" },
  { value: "Hostel B2", label: "Hostel B2" },
  { value: "Hostel B3", label: "Hostel B3" },
  { value: "Hostel B4", label: "Hostel B4" },
  { value: "Hostel B5", label: "Hostel B5" },
  { value: "Hostel G1", label: "Hostel G1" },
  { value: "Hostel G2", label: "Hostel G2" },
  { value: "Hostel G3", label: "Hostel G3" },
  { value: "Hostel G4", label: "Hostel G4" },
  { value: "Hostel G5", label: "Hostel G5" },
  { value: "Hostel G6", label: "Hostel G6" },
  { value: "Hostel Y4", label: "Hostel Y4" },
  { value: "Hostel I2", label: "Hostel I2" },
  { value: "Hostel I3", label: "Hostel I3" },
  { value: "Hostel O3", label: "Hostel O3" },
  { value: "Hostel O4", label: "Hostel O4" },
  { value: "CSE Department", label: "CSE Department" },
  { value: "Mechanical Department", label: "Mechanical Department" },
  { value: "Bio Department", label: "Bifauult o Department" },
  { value: "Civil Department", label: "Civil Department" },
  { value: "Electrical Department", label: "Electrical Department" },
  { value: "Chemistry Department", label: "Chemistry Department" },
  { value: "Physics Department", label: "Physics Department" },
  { value: "Materials Department", label: "Materials Department" },
  { value: "Maths Department", label: "Maths Department" },
  { value: "SME", label: "SME" },
  { value: "SOLA", label: "SOLA" },
  { value: "MBA", label: "MBA" },
  { value: "Cricket Ground", label: "Cricket Ground" },
  { value: "Hockey Ground", label: "Hockey Ground" },
  { value: "Basketball Court", label: "Basketball Court" },
];
